services:
  nginx:
    build: ./frontend
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - fast-api

  fast-api:
    build: ./backend
    container_name: fast-api
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - ./music_file:/app/music_file
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_CONNECT_URI=mongodb://root:nycuee@mongo:27017/test?authSource=admin

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nycuee
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: nycuee
      ME_CONFIG_MONGODB_URL: mongodb://root:nycuee@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
