services:
  nginx:
    build: 
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL_PROD}
    container_name: ${PROJECT_PREFIX:-lightdance}-nginx-${USER:-czli}
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      app-network:
        aliases:
          - nginx

  backend:
    build: ./backend
    container_name: ${PROJECT_PREFIX:-lightdance}-backend-${USER:-czli}
    ports:
      - ${API_PORT:-8000}:8000
    volumes:
      - ./music_file:/music
      # Development volume mount - controlled by DEV_MODE environment variable
      - ${DEV_MODE:+./backend:/app}
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_CONNECT_URI=mongodb://${MONGO_USERNAME:-user}:${MONGO_PASSWORD:-password}@mongo:27017
      - APP_RELOAD=${DEV_MODE:-false}
      - MUSIC_FILE_PATH=/music
    networks:
      app-network:
        aliases:
          - backend

  mongo:
    image: mongo
    container_name: ${PROJECT_PREFIX:-lightdance}-mongo-${USER:-czli}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-user}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    # # This port should not be exposed
    # ports:
    #   - 27017:27017
    volumes:
      - ./db:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      app-network:
        aliases:
          - mongo

  mongo-express:
    image: mongo-express
    container_name: ${PROJECT_PREFIX:-lightdance}-express-${USER:-czli}
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-user}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-password}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME:-user}:${MONGO_PASSWORD:-password}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      app-network:
        aliases:
          - mongo-express

networks:
  app-network:
    driver: bridge
    name: ${PROJECT_PREFIX:-lightdance}-network-${USER:-czli}